name: ci

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Validate Docker Compose
        run: |
          docker-compose config
          
      - name: Docker Compose Service Test
        run: |
          docker-compose up -d
          sleep 30
          docker-compose ps
          curl -f http://localhost:8086/ping || exit 1
          curl -f http://localhost:3000/api/health || exit 1
          docker-compose down -v

  validate-telegraf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Validate Telegraf Config
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/telegraf:/etc/telegraf \
            telegraf:1.16.3 \
            telegraf --config /etc/telegraf/telegraf.conf --test

  validate-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check Required Files
        run: |
          test -f docker-compose.yml
          test -f README.md
          test -d telegraf
          test -f telegraf/telegraf.conf
          test -d mibs
          
          echo "All required files and directories exist"